configfile: "config.yaml"

rule all:
    input:
        collect("results/{sample}_processed.tar.gz", sample = config["samples"])

module DatasetProcessing:
    snakefile: "DatasetProcessing.smk"
    config: config
    pathvars:
        input_dataset = "resources/{sample}.tar.gz",
        output_dataset = "results/{sample}_processed.tar.gz",


use rule * from DatasetProcessing as dataset_*





