[workspace]
authors = ["Lukas Heinrich <lukas.heinrich@cern.ch>"]
channels = ["conda-forge", "bioconda"]
name = "datasetsnake"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.16.3,<10"
